### ISSUE TITLE
missing license for test24.mp3

### ISSUE THREAD

**Issue by aviau** [hjfreyer/taglib-go#11]
Is there a missing license for test24.mp3? We need to know this for Debian.

**Comment by hjfreyer** [comment]
I'm sure I copied it from another id3 tag test suite, since I don't recognize the audio itself, but I don't actually have any evidence of that. Consequently, I've replaced test24.mp3 with audio licensed under CC-BY 4.0 in change d150ea9.

Please reopen if that's insufficient!

**Comment by aviau** [comment]
Thank you!
