### ISSUE TITLE
panic when len(id3_frame.Content) == 1 (or 0)

### ISSUE THREAD

**Issue by mpl** [hjfreyer/taglib-go#7]
Example of a culprit:
https://granivo.re/tmp/Infected_Mushroom-Muse_breaks.mp3

```  
tag, err := taglib.Decode(f, 5000000)
  if err != nil {
    log.Fatal(err)
  }
  println(tag.Genre())
```

will panic, because it turns out the frame Content is of length 1.

**Comment by hjfreyer** [comment]
Thanks so much for the fix! Subtle little error that...

I wonder whether we could reproduce this in a test case; perhaps copy the tags into a public domain audio file and add it to testdata/?

**Comment by mpl** [comment]
Definitely worth a try. I can look into it later if you want, but I'm really not familiar with the code and spec (I got lucky as this one bug was easy to find) so it might take me a while.
